/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ScrapsRouteImport } from './routes/scraps'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrapsIndexRouteImport } from './routes/scraps.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ScrapsSlugRouteImport } from './routes/scraps.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapsRoute = ScrapsRouteImport.update({
  id: '/scraps',
  path: '/scraps',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapsIndexRoute = ScrapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScrapsRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScrapsSlugRoute = ScrapsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScrapsRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/scraps': typeof ScrapsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks': typeof TasksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/scraps': typeof ScrapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/scraps': typeof ScrapsRouteWithChildren
  '/tasks': typeof TasksRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/scraps'
    | '/tasks'
    | '/admin/settings'
    | '/admin/tasks'
    | '/articles/$slug'
    | '/scraps/$slug'
    | '/admin/'
    | '/articles/'
    | '/scraps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks'
    | '/admin/settings'
    | '/admin/tasks'
    | '/articles/$slug'
    | '/scraps/$slug'
    | '/admin'
    | '/articles'
    | '/scraps'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/scraps'
    | '/tasks'
    | '/admin/settings'
    | '/admin/tasks'
    | '/articles/$slug'
    | '/scraps/$slug'
    | '/admin/'
    | '/articles/'
    | '/scraps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ScrapsRoute: typeof ScrapsRouteWithChildren
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraps': {
      id: '/scraps'
      path: '/scraps'
      fullPath: '/scraps'
      preLoaderRoute: typeof ScrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraps/': {
      id: '/scraps/'
      path: '/'
      fullPath: '/scraps/'
      preLoaderRoute: typeof ScrapsIndexRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scraps/$slug': {
      id: '/scraps/$slug'
      path: '/$slug'
      fullPath: '/scraps/$slug'
      preLoaderRoute: typeof ScrapsSlugRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ScrapsRouteChildren {
  ScrapsSlugRoute: typeof ScrapsSlugRoute
  ScrapsIndexRoute: typeof ScrapsIndexRoute
}

const ScrapsRouteChildren: ScrapsRouteChildren = {
  ScrapsSlugRoute: ScrapsSlugRoute,
  ScrapsIndexRoute: ScrapsIndexRoute,
}

const ScrapsRouteWithChildren =
  ScrapsRoute._addFileChildren(ScrapsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  ScrapsRoute: ScrapsRouteWithChildren,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
