/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrapsRouteImport } from './routes/scraps'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrapsIndexRouteImport } from './routes/scraps.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ScrapsSlugRouteImport } from './routes/scraps.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as ApiBlogAssetsProxyRouteImport } from './routes/api.blog-assets.proxy'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogSlugRouteImport } from './routes/admin.blog.$slug'
import { Route as ApiBlogAssetsTempSplatRouteImport } from './routes/api.blog-assets.temp.$'

const ScrapsRoute = ScrapsRouteImport.update({
  id: '/scraps',
  path: '/scraps',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapsIndexRoute = ScrapsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScrapsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScrapsSlugRoute = ScrapsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScrapsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ApiBlogAssetsProxyRoute = ApiBlogAssetsProxyRouteImport.update({
  id: '/api/blog-assets/proxy',
  path: '/api/blog-assets/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogSlugRoute = AdminBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ApiBlogAssetsTempSplatRoute = ApiBlogAssetsTempSplatRouteImport.update({
  id: '/api/blog-assets/temp/$',
  path: '/api/blog-assets/temp/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/author': typeof AuthorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/scraps': typeof ScrapsRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/author': typeof AuthorRoute
  '/contact': typeof ContactRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/scraps': typeof ScrapsIndexRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/author': typeof AuthorRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/scraps': typeof ScrapsRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/api/contact': typeof ApiContactRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/scraps/$slug': typeof ScrapsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/scraps/': typeof ScrapsIndexRoute
  '/admin/blog/$slug': typeof AdminBlogSlugRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/api/blog-assets/proxy': typeof ApiBlogAssetsProxyRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/blog-assets/temp/$': typeof ApiBlogAssetsTempSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/author'
    | '/blog'
    | '/contact'
    | '/scraps'
    | '/admin/blog'
    | '/admin/settings'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/scraps/'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/api/blog-assets/proxy'
    | '/admin/blog/'
    | '/api/blog-assets/temp/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/author'
    | '/contact'
    | '/admin/settings'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/admin'
    | '/articles'
    | '/blog'
    | '/scraps'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/api/blog-assets/proxy'
    | '/admin/blog'
    | '/api/blog-assets/temp/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/author'
    | '/blog'
    | '/contact'
    | '/scraps'
    | '/admin/blog'
    | '/admin/settings'
    | '/api/contact'
    | '/articles/$slug'
    | '/blog/$slug'
    | '/scraps/$slug'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/scraps/'
    | '/admin/blog/$slug'
    | '/admin/blog/new'
    | '/api/blog-assets/proxy'
    | '/admin/blog/'
    | '/api/blog-assets/temp/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthorRoute: typeof AuthorRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ScrapsRoute: typeof ScrapsRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
  ApiBlogAssetsProxyRoute: typeof ApiBlogAssetsProxyRoute
  ApiBlogAssetsTempSplatRoute: typeof ApiBlogAssetsTempSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scraps': {
      id: '/scraps'
      path: '/scraps'
      fullPath: '/scraps'
      preLoaderRoute: typeof ScrapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scraps/': {
      id: '/scraps/'
      path: '/'
      fullPath: '/scraps/'
      preLoaderRoute: typeof ScrapsIndexRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scraps/$slug': {
      id: '/scraps/$slug'
      path: '/$slug'
      fullPath: '/scraps/$slug'
      preLoaderRoute: typeof ScrapsSlugRouteImport
      parentRoute: typeof ScrapsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/api/blog-assets/proxy': {
      id: '/api/blog-assets/proxy'
      path: '/api/blog-assets/proxy'
      fullPath: '/api/blog-assets/proxy'
      preLoaderRoute: typeof ApiBlogAssetsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$slug': {
      id: '/admin/blog/$slug'
      path: '/$slug'
      fullPath: '/admin/blog/$slug'
      preLoaderRoute: typeof AdminBlogSlugRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/api/blog-assets/temp/$': {
      id: '/api/blog-assets/temp/$'
      path: '/api/blog-assets/temp/$'
      fullPath: '/api/blog-assets/temp/$'
      preLoaderRoute: typeof ApiBlogAssetsTempSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogSlugRoute: typeof AdminBlogSlugRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogSlugRoute: AdminBlogSlugRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ScrapsRouteChildren {
  ScrapsSlugRoute: typeof ScrapsSlugRoute
  ScrapsIndexRoute: typeof ScrapsIndexRoute
}

const ScrapsRouteChildren: ScrapsRouteChildren = {
  ScrapsSlugRoute: ScrapsSlugRoute,
  ScrapsIndexRoute: ScrapsIndexRoute,
}

const ScrapsRouteWithChildren =
  ScrapsRoute._addFileChildren(ScrapsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthorRoute: AuthorRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ScrapsRoute: ScrapsRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
  ApiBlogAssetsProxyRoute: ApiBlogAssetsProxyRoute,
  ApiBlogAssetsTempSplatRoute: ApiBlogAssetsTempSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
